import { Octokit } from "octokit";
import { getOrCreateOrganization, canReviewPR, incrementReviewCount, logReview } from "../supabase/organizations";

export async function handlePullRequestEvent(payload: any) {
  const action = payload.action;
  const pr = payload.pull_request;
  const repo = payload.repository;
  
  // Security Fix: Strict type checking to prevent prototype pollution or malformed payloads
  if (!pr || typeof pr.number !== 'number') {
    return { status: "ignored", reason: "Invalid PR payload" };
  }
  
  if (!repo || typeof repo.full_name !== 'string' || !repo.full_name.match(/^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/)) {
    return { status: "ignored", reason: "Invalid repository format" };
  }

  // We only care about newly opened or synchronized (updated) PRs
  if (!["opened", "synchronize"].includes(action)) {
    return { status: "ignored", reason: "Action not supported" };
  }

  const installationId = payload.installation?.id;
  if (!installationId) {
    return { status: "ignored", reason: "No GitHub App installation ID found" };
  }

  // 1. Ensure Organization exists in Supabase
  const org = await getOrCreateOrganization(installationId, repo.owner.login);

  // 2. Enforce Monthly Limits (5 for Free, 100 for Pro)
  const isAllowed = await canReviewPR(org);
  if (!isAllowed) {
    console.log(`Rate limit exceeded for ${repo.full_name} (${org.plan_tier} tier)`);
    await logReview(org.id, repo.full_name, pr.number, "rate_limited");
    return { status: "rate_limited", reason: "Monthly PR review quota exceeded." };
  }

  console.log(`Processing PR #${pr.number} in ${repo.full_name}`);

  const octokit = new Octokit({
    auth: process.env.GITHUB_PAT || process.env.GITHUB_TOKEN,
  });

  try {
    // 1. Fetch the raw diff safely
    const { data: diff } = await octokit.request(
      `GET /repos/{owner}/{repo}/pulls/{pull_number}`,
      {
        owner: repo.owner.login,
        repo: repo.name,
        pull_number: pr.number,
        mediaType: {
          format: "diff",
        },
      }
    );

    // 2. Generate the review via Anthropic
    const { generateReview } = await import("../ai/reviewer");
    const reviewMarkdown = await generateReview(String(diff));

    // 3. Post the comment back to the GitHub PR safely
    const formattedComment = `🤖 **AutoReview AI Analysis**\n\n${reviewMarkdown}\n\n---\n*Generated by AutoReview. Devs save 4 hours/week parsing diffs.*`;

    await octokit.request(
      `POST /repos/{owner}/{repo}/issues/{issue_number}/comments`,
      {
        owner: repo.owner.login,
        repo: repo.name,
        issue_number: pr.number,
        body: formattedComment,
      }
    );

    console.log(`Successfully reviewed PR #${pr.number}`);
    
    // 4. Update Database Usage Metrics
    await incrementReviewCount(org.id);
    // Rough estimate of tokens for logs (actual tracking would pull from the Anthropic response headers)
    await logReview(org.id, repo.full_name, pr.number, "success", diff.length / 4);

    return { status: "success", reviewLength: reviewMarkdown.length };

  } catch (error) {
    console.error(`Failed to review PR #${pr.number}:`, error);
    throw error;
  }
}
